services:
  - type: web
    name: smartcivic-vit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
      - key: MAIL_USERNAME
        value: ""
      - key: MAIL_PASSWORD
        value: ""
